name: Linux build

on: [push, pull_request]

env:
  FMOD_VER: 44464
  FMOD_SOVER: 4.44.64

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        build_type: [Release]
        # This is just so the job and artefact names look nicer...
        serveronly: ["", "SERVERONLY"]
        include:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
        exclude:
          - os: ubuntu-24.04-arm
            serveronly: ""

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies for Linux
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install g++ make cmake libsdl1.2-dev mercurial zlib1g-dev libbz2-dev libjpeg-dev libfluidsynth-dev libgtk2.0-dev timidity nasm libgl1-mesa-dev libssl-dev tar libglew-dev wget libopus-dev
        
        if [[ "${{ matrix.serveronly }}" == "" ]]; then
          wget https://github.com/DrinkyBird/zan-ci-deps/releases/download/ci-dependencies/fmodapi${FMOD_VER}linux.tar.gz
          tar xf fmodapi${FMOD_VER}linux.tar.gz
          echo "FMOD_INCLUDE_DIR=${PWD}/fmodapi${FMOD_VER}linux/api/inc" >> $GITHUB_ENV
          echo "FMOD_LIBRARY=${PWD}/fmodapi${FMOD_VER}linux/api/lib/libfmodex64-${FMOD_SOVER}.so" >> $GITHUB_ENV
        fi

    - name: Configure CMake
      run: >
        if [[ "${{ matrix.serveronly }}" == "SERVERONLY" ]]; then export SERVERONLY=ON; fi
        
        cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DSERVERONLY=${SERVERONLY}
        -DRELEASE_WITH_DEBUG_FILE=ON

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} -j $(nproc)

    - name: Create package
      shell: bash
      run: |
        mkdir package
        if [[ "${{ runner.os }}" == 'Linux' ]]; then
          cp ${{ steps.strings.outputs.build-output-dir }}/zandronum* package
          cp ${{ steps.strings.outputs.build-output-dir }}/*.pk3 package
          cp ${{ steps.strings.outputs.build-output-dir }}/*.so package || true
          cp ${FMOD_LIBRARY} package || true
        fi

    - name: Upload artefacts
      uses: actions/upload-artifact@v4
      with:
        path: package
        name: ${{ matrix.os }} ${{ matrix.build_type }} ${{ matrix.serveronly }}
